# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "ABOUT"
  url = "#about"
  weight = 10

[[main]]
  name = "PROJECTS"
  url = "/project_landing"
  weight = 20

[[main]]
  name = "PUBLICATIONS"
  url = "/publication/"
  weight = 25

[[main]]
  name = "BLOG"
  url = "/post"
  weight = 40

[[main]]
  name = "CV & RÉSUMÉ"
  identifier = "cv"
  url = "#"
  weight = 50
  
[[main]]
  name = "CV <i class='fas fa-copy'></i>"
  parent = "cv"
  url = "/cv/index.html"
  weight = 50.1
  
[[main]]
  name = "RÉSUMÉ <i class='fas fa-file'></i>"
  parent = "cv"
  url = "/cv/resume.html"
  weight = 50.2

[[main]]
  name = "GALLERY"
  identifier = "gallery"
  url = "#"
  weight = 30

[[main]]
  name = "Monsanto Photos <i class='fas fa-leaf'></i>"
  parent = "gallery"
  url = "/gallery/monsanto/"
  weight = 30.1

  [[main]]
  name = "Int. 2012"
  parent = "monsanto photos"
  url = "/gallery/monsanto/2012/"
  weight = 30.11

[[main]]
  name = "Int. 2014"
  parent = "monsanto"
  url = "/gallery/monsanto/2014/"
  weight = 30.12

[[main]]
  name = "Int. 2015"
  parent = "monsanto"
  url = "/gallery/monsanto/2015/"
  weight = 30.13

[[main]]
  name = "Int. 2016"
  parent = "monsanto"
  url = "/gallery/monsanto/2016/"
  weight = 30.14

[[main]]
  name = "Int. 2017"
  parent = "monsanto"
  url = "/gallery/monsanto/2017/"
  weight = 30.15

[[main]]
  name = "Field"
  parent = "monsanto"
  url = "/gallery/monsanto/field/"
  weight = 30.16


[[main]]
  name = "PhD Photos <i class='fas fa-graduation-cap'></i>"
  parent = "gallery"
  url = "/gallery/phd/"
  weight = 30.2

[[main]]
  name = "CONTACT"
  url = "/contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
